// Configuration loader for browser environment
// This file can be generated by your build process or server

window.ENV_VARS = {
    SUPABASE_URL: 'https://lmmacdkoiwhmjhscjssa.supabase.co',
    SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtbWFjZGtvaXdobWpoc2Nqc3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjAxNjEsImV4cCI6MjA2OTk5NjE2MX0.38HIXiAtv0U93jzqpY1wHSiPgf1C2VepKIJhsJwbaGw'
}

console.log('Environment variables loaded') 